# Generated by Django 3.1 on 2023-10-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_catimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimage',
            name='images',
            field=models.ImageField(upload_to='coverimg'),
        ),
    ]
